"""initial schema

Creates every table from the declarative models rather than restating them as
``op.create_table`` calls. For the *first* migration this is deliberate: a
hand-transcribed copy of an eleven-table schema is a place for the migration and
the models to silently disagree. Later migrations are ordinary autogenerated
diffs against this baseline.

Revision ID: 0001
"""

from alembic import op

from app.db.base import Base
from app.db import models  # noqa: F401 - populates Base.metadata

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
